/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.EmpresasApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmpresasApi', function() {
    describe('createEmpresa', function() {
      it('should call createEmpresa successfully', function(done) {
        //uncomment below and update the code to test createEmpresa
        //instance.createEmpresa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEmpresa', function() {
      it('should call deleteEmpresa successfully', function(done) {
        //uncomment below and update the code to test deleteEmpresa
        //instance.deleteEmpresa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEmpresa', function() {
      it('should call getEmpresa successfully', function(done) {
        //uncomment below and update the code to test getEmpresa
        //instance.getEmpresa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEmpresas', function() {
      it('should call getEmpresas successfully', function(done) {
        //uncomment below and update the code to test getEmpresas
        //instance.getEmpresas(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEmpresa', function() {
      it('should call updateEmpresa successfully', function(done) {
        //uncomment below and update the code to test updateEmpresa
        //instance.updateEmpresa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validarEmpresa', function() {
      it('should call validarEmpresa successfully', function(done) {
        //uncomment below and update the code to test validarEmpresa
        //instance.validarEmpresa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
