/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.PersonasApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonasApi', function() {
    describe('createPersona', function() {
      it('should call createPersona successfully', function(done) {
        //uncomment below and update the code to test createPersona
        //instance.createPersona(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePersona', function() {
      it('should call deletePersona successfully', function(done) {
        //uncomment below and update the code to test deletePersona
        //instance.deletePersona(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPersona', function() {
      it('should call getPersona successfully', function(done) {
        //uncomment below and update the code to test getPersona
        //instance.getPersona(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPersonas', function() {
      it('should call getPersonas successfully', function(done) {
        //uncomment below and update the code to test getPersonas
        //instance.getPersonas(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePersona', function() {
      it('should call updatePersona successfully', function(done) {
        //uncomment below and update the code to test updatePersona
        //instance.updatePersona(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validarPersona', function() {
      it('should call validarPersona successfully', function(done) {
        //uncomment below and update the code to test validarPersona
        //instance.validarPersona(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
