/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ActionMessage from './model/ActionMessage';
import ActualizarEstadoContactoRequest from './model/ActualizarEstadoContactoRequest';
import ContactoSolicitado from './model/ContactoSolicitado';
import ContactoSolicitadoInput from './model/ContactoSolicitadoInput';
import ContactoSolicitadoListResponse from './model/ContactoSolicitadoListResponse';
import ContactoSolicitadoResponse from './model/ContactoSolicitadoResponse';
import Empresa from './model/Empresa';
import EmpresaInput from './model/EmpresaInput';
import EmpresaListResponse from './model/EmpresaListResponse';
import EmpresaResponse from './model/EmpresaResponse';
import EmpresaValidationResponse from './model/EmpresaValidationResponse';
import EmpresaValidationResult from './model/EmpresaValidationResult';
import ErrorResponse from './model/ErrorResponse';
import Estadisticas from './model/Estadisticas';
import EstadisticasResponse from './model/EstadisticasResponse';
import MessageResponse from './model/MessageResponse';
import Persona from './model/Persona';
import PersonaCVCiego from './model/PersonaCVCiego';
import PersonaCursosInner from './model/PersonaCursosInner';
import PersonaIdiomasInner from './model/PersonaIdiomasInner';
import PersonaInput from './model/PersonaInput';
import PersonaListResponse from './model/PersonaListResponse';
import PersonaResponse from './model/PersonaResponse';
import PersonaValidationResponse from './model/PersonaValidationResponse';
import PersonaValidationResult from './model/PersonaValidationResult';
import AdministracinApi from './api/AdministracinApi';
import EmpresasApi from './api/EmpresasApi';
import HealthApi from './api/HealthApi';
import PersonasApi from './api/PersonasApi';


/**
* API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProviEmpleaApi = require('index'); // See note below*.
* var xxxSvc = new ProviEmpleaApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProviEmpleaApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProviEmpleaApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProviEmpleaApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ActionMessage model constructor.
     * @property {module:model/ActionMessage}
     */
    ActionMessage,

    /**
     * The ActualizarEstadoContactoRequest model constructor.
     * @property {module:model/ActualizarEstadoContactoRequest}
     */
    ActualizarEstadoContactoRequest,

    /**
     * The ContactoSolicitado model constructor.
     * @property {module:model/ContactoSolicitado}
     */
    ContactoSolicitado,

    /**
     * The ContactoSolicitadoInput model constructor.
     * @property {module:model/ContactoSolicitadoInput}
     */
    ContactoSolicitadoInput,

    /**
     * The ContactoSolicitadoListResponse model constructor.
     * @property {module:model/ContactoSolicitadoListResponse}
     */
    ContactoSolicitadoListResponse,

    /**
     * The ContactoSolicitadoResponse model constructor.
     * @property {module:model/ContactoSolicitadoResponse}
     */
    ContactoSolicitadoResponse,

    /**
     * The Empresa model constructor.
     * @property {module:model/Empresa}
     */
    Empresa,

    /**
     * The EmpresaInput model constructor.
     * @property {module:model/EmpresaInput}
     */
    EmpresaInput,

    /**
     * The EmpresaListResponse model constructor.
     * @property {module:model/EmpresaListResponse}
     */
    EmpresaListResponse,

    /**
     * The EmpresaResponse model constructor.
     * @property {module:model/EmpresaResponse}
     */
    EmpresaResponse,

    /**
     * The EmpresaValidationResponse model constructor.
     * @property {module:model/EmpresaValidationResponse}
     */
    EmpresaValidationResponse,

    /**
     * The EmpresaValidationResult model constructor.
     * @property {module:model/EmpresaValidationResult}
     */
    EmpresaValidationResult,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Estadisticas model constructor.
     * @property {module:model/Estadisticas}
     */
    Estadisticas,

    /**
     * The EstadisticasResponse model constructor.
     * @property {module:model/EstadisticasResponse}
     */
    EstadisticasResponse,

    /**
     * The MessageResponse model constructor.
     * @property {module:model/MessageResponse}
     */
    MessageResponse,

    /**
     * The Persona model constructor.
     * @property {module:model/Persona}
     */
    Persona,

    /**
     * The PersonaCVCiego model constructor.
     * @property {module:model/PersonaCVCiego}
     */
    PersonaCVCiego,

    /**
     * The PersonaCursosInner model constructor.
     * @property {module:model/PersonaCursosInner}
     */
    PersonaCursosInner,

    /**
     * The PersonaIdiomasInner model constructor.
     * @property {module:model/PersonaIdiomasInner}
     */
    PersonaIdiomasInner,

    /**
     * The PersonaInput model constructor.
     * @property {module:model/PersonaInput}
     */
    PersonaInput,

    /**
     * The PersonaListResponse model constructor.
     * @property {module:model/PersonaListResponse}
     */
    PersonaListResponse,

    /**
     * The PersonaResponse model constructor.
     * @property {module:model/PersonaResponse}
     */
    PersonaResponse,

    /**
     * The PersonaValidationResponse model constructor.
     * @property {module:model/PersonaValidationResponse}
     */
    PersonaValidationResponse,

    /**
     * The PersonaValidationResult model constructor.
     * @property {module:model/PersonaValidationResult}
     */
    PersonaValidationResult,

    /**
    * The AdministracinApi service constructor.
    * @property {module:api/AdministracinApi}
    */
    AdministracinApi,

    /**
    * The EmpresasApi service constructor.
    * @property {module:api/EmpresasApi}
    */
    EmpresasApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The PersonasApi service constructor.
    * @property {module:api/PersonasApi}
    */
    PersonasApi
};
