/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActualizarEstadoContactoRequest model module.
 * @module model/ActualizarEstadoContactoRequest
 * @version 1.0.0
 */
class ActualizarEstadoContactoRequest {
    /**
     * Constructs a new <code>ActualizarEstadoContactoRequest</code>.
     * @alias module:model/ActualizarEstadoContactoRequest
     * @param estado {module:model/ActualizarEstadoContactoRequest.EstadoEnum} 
     */
    constructor(estado) { 
        
        ActualizarEstadoContactoRequest.initialize(this, estado);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, estado) { 
        obj['estado'] = estado;
    }

    /**
     * Constructs a <code>ActualizarEstadoContactoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActualizarEstadoContactoRequest} obj Optional instance to populate.
     * @return {module:model/ActualizarEstadoContactoRequest} The populated <code>ActualizarEstadoContactoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActualizarEstadoContactoRequest();

            if (data.hasOwnProperty('estado')) {
                obj['estado'] = ApiClient.convertToType(data['estado'], 'String');
            }
            if (data.hasOwnProperty('notas_admin')) {
                obj['notas_admin'] = ApiClient.convertToType(data['notas_admin'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActualizarEstadoContactoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActualizarEstadoContactoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ActualizarEstadoContactoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['estado'] && !(typeof data['estado'] === 'string' || data['estado'] instanceof String)) {
            throw new Error("Expected the field `estado` to be a primitive type in the JSON string but got " + data['estado']);
        }
        // ensure the json data is a string
        if (data['notas_admin'] && !(typeof data['notas_admin'] === 'string' || data['notas_admin'] instanceof String)) {
            throw new Error("Expected the field `notas_admin` to be a primitive type in the JSON string but got " + data['notas_admin']);
        }

        return true;
    }


}

ActualizarEstadoContactoRequest.RequiredProperties = ["estado"];

/**
 * @member {module:model/ActualizarEstadoContactoRequest.EstadoEnum} estado
 */
ActualizarEstadoContactoRequest.prototype['estado'] = undefined;

/**
 * @member {String} notas_admin
 */
ActualizarEstadoContactoRequest.prototype['notas_admin'] = undefined;





/**
 * Allowed values for the <code>estado</code> property.
 * @enum {String}
 * @readonly
 */
ActualizarEstadoContactoRequest['EstadoEnum'] = {

    /**
     * value: "pendiente"
     * @const
     */
    "pendiente": "pendiente",

    /**
     * value: "contactado"
     * @const
     */
    "contactado": "contactado",

    /**
     * value: "entrevista"
     * @const
     */
    "entrevista": "entrevista",

    /**
     * value: "seleccionado"
     * @const
     */
    "seleccionado": "seleccionado",

    /**
     * value: "no-seleccionado"
     * @const
     */
    "no-seleccionado": "no-seleccionado",

    /**
     * value: "proceso-cerrado"
     * @const
     */
    "proceso-cerrado": "proceso-cerrado"
};



export default ActualizarEstadoContactoRequest;

