/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactoSolicitado from './ContactoSolicitado';

/**
 * The ContactoSolicitadoResponse model module.
 * @module model/ContactoSolicitadoResponse
 * @version 1.0.0
 */
class ContactoSolicitadoResponse {
    /**
     * Constructs a new <code>ContactoSolicitadoResponse</code>.
     * @alias module:model/ContactoSolicitadoResponse
     * @param success {Boolean} 
     * @param data {module:model/ContactoSolicitado} 
     */
    constructor(success, data) { 
        
        ContactoSolicitadoResponse.initialize(this, success, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, data) { 
        obj['success'] = success;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ContactoSolicitadoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactoSolicitadoResponse} obj Optional instance to populate.
     * @return {module:model/ContactoSolicitadoResponse} The populated <code>ContactoSolicitadoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactoSolicitadoResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ContactoSolicitado.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactoSolicitadoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactoSolicitadoResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactoSolicitadoResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          ContactoSolicitado.validateJSON(data['data']);
        }

        return true;
    }


}

ContactoSolicitadoResponse.RequiredProperties = ["success", "data"];

/**
 * @member {Boolean} success
 */
ContactoSolicitadoResponse.prototype['success'] = undefined;

/**
 * @member {module:model/ContactoSolicitado} data
 */
ContactoSolicitadoResponse.prototype['data'] = undefined;






export default ContactoSolicitadoResponse;

