/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Empresa from './Empresa';
import Persona from './Persona';

/**
 * The ContactoSolicitado model module.
 * @module model/ContactoSolicitado
 * @version 1.0.0
 */
class ContactoSolicitado {
    /**
     * Constructs a new <code>ContactoSolicitado</code>.
     * Solicitud de contacto entre empresa y talento
     * @alias module:model/ContactoSolicitado
     */
    constructor() { 
        
        ContactoSolicitado.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContactoSolicitado</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactoSolicitado} obj Optional instance to populate.
     * @return {module:model/ContactoSolicitado} The populated <code>ContactoSolicitado</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactoSolicitado();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('empresa_id')) {
                obj['empresa_id'] = ApiClient.convertToType(data['empresa_id'], 'String');
            }
            if (data.hasOwnProperty('persona_id')) {
                obj['persona_id'] = ApiClient.convertToType(data['persona_id'], 'String');
            }
            if (data.hasOwnProperty('estado')) {
                obj['estado'] = ApiClient.convertToType(data['estado'], 'String');
            }
            if (data.hasOwnProperty('notas_admin')) {
                obj['notas_admin'] = ApiClient.convertToType(data['notas_admin'], 'String');
            }
            if (data.hasOwnProperty('fecha_contacto')) {
                obj['fecha_contacto'] = ApiClient.convertToType(data['fecha_contacto'], 'Date');
            }
            if (data.hasOwnProperty('fecha_entrevista')) {
                obj['fecha_entrevista'] = ApiClient.convertToType(data['fecha_entrevista'], 'Date');
            }
            if (data.hasOwnProperty('fecha_resultado')) {
                obj['fecha_resultado'] = ApiClient.convertToType(data['fecha_resultado'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('empresa')) {
                obj['empresa'] = Empresa.constructFromObject(data['empresa']);
            }
            if (data.hasOwnProperty('persona')) {
                obj['persona'] = Persona.constructFromObject(data['persona']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactoSolicitado</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactoSolicitado</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['empresa_id'] && !(typeof data['empresa_id'] === 'string' || data['empresa_id'] instanceof String)) {
            throw new Error("Expected the field `empresa_id` to be a primitive type in the JSON string but got " + data['empresa_id']);
        }
        // ensure the json data is a string
        if (data['persona_id'] && !(typeof data['persona_id'] === 'string' || data['persona_id'] instanceof String)) {
            throw new Error("Expected the field `persona_id` to be a primitive type in the JSON string but got " + data['persona_id']);
        }
        // ensure the json data is a string
        if (data['estado'] && !(typeof data['estado'] === 'string' || data['estado'] instanceof String)) {
            throw new Error("Expected the field `estado` to be a primitive type in the JSON string but got " + data['estado']);
        }
        // ensure the json data is a string
        if (data['notas_admin'] && !(typeof data['notas_admin'] === 'string' || data['notas_admin'] instanceof String)) {
            throw new Error("Expected the field `notas_admin` to be a primitive type in the JSON string but got " + data['notas_admin']);
        }
        // validate the optional field `empresa`
        if (data['empresa']) { // data not null
          Empresa.validateJSON(data['empresa']);
        }
        // validate the optional field `persona`
        if (data['persona']) { // data not null
          Persona.validateJSON(data['persona']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ContactoSolicitado.prototype['id'] = undefined;

/**
 * @member {String} empresa_id
 */
ContactoSolicitado.prototype['empresa_id'] = undefined;

/**
 * @member {String} persona_id
 */
ContactoSolicitado.prototype['persona_id'] = undefined;

/**
 * @member {module:model/ContactoSolicitado.EstadoEnum} estado
 */
ContactoSolicitado.prototype['estado'] = undefined;

/**
 * @member {String} notas_admin
 */
ContactoSolicitado.prototype['notas_admin'] = undefined;

/**
 * @member {Date} fecha_contacto
 */
ContactoSolicitado.prototype['fecha_contacto'] = undefined;

/**
 * @member {Date} fecha_entrevista
 */
ContactoSolicitado.prototype['fecha_entrevista'] = undefined;

/**
 * @member {Date} fecha_resultado
 */
ContactoSolicitado.prototype['fecha_resultado'] = undefined;

/**
 * @member {Date} created_at
 */
ContactoSolicitado.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ContactoSolicitado.prototype['updated_at'] = undefined;

/**
 * @member {module:model/Empresa} empresa
 */
ContactoSolicitado.prototype['empresa'] = undefined;

/**
 * @member {module:model/Persona} persona
 */
ContactoSolicitado.prototype['persona'] = undefined;





/**
 * Allowed values for the <code>estado</code> property.
 * @enum {String}
 * @readonly
 */
ContactoSolicitado['EstadoEnum'] = {

    /**
     * value: "pendiente"
     * @const
     */
    "pendiente": "pendiente",

    /**
     * value: "contactado"
     * @const
     */
    "contactado": "contactado",

    /**
     * value: "entrevista"
     * @const
     */
    "entrevista": "entrevista",

    /**
     * value: "seleccionado"
     * @const
     */
    "seleccionado": "seleccionado",

    /**
     * value: "no-seleccionado"
     * @const
     */
    "no-seleccionado": "no-seleccionado",

    /**
     * value: "proceso-cerrado"
     * @const
     */
    "proceso-cerrado": "proceso-cerrado"
};



export default ContactoSolicitado;

