/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactoSolicitado from './ContactoSolicitado';

/**
 * The ContactoSolicitadoListResponse model module.
 * @module model/ContactoSolicitadoListResponse
 * @version 1.0.0
 */
class ContactoSolicitadoListResponse {
    /**
     * Constructs a new <code>ContactoSolicitadoListResponse</code>.
     * @alias module:model/ContactoSolicitadoListResponse
     * @param success {Boolean} 
     * @param data {Array.<module:model/ContactoSolicitado>} 
     */
    constructor(success, data) { 
        
        ContactoSolicitadoListResponse.initialize(this, success, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, data) { 
        obj['success'] = success;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ContactoSolicitadoListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactoSolicitadoListResponse} obj Optional instance to populate.
     * @return {module:model/ContactoSolicitadoListResponse} The populated <code>ContactoSolicitadoListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactoSolicitadoListResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ContactoSolicitado]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactoSolicitadoListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactoSolicitadoListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactoSolicitadoListResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ContactoSolicitado.validateJSON(item);
            };
        }

        return true;
    }


}

ContactoSolicitadoListResponse.RequiredProperties = ["success", "data"];

/**
 * @member {Boolean} success
 */
ContactoSolicitadoListResponse.prototype['success'] = undefined;

/**
 * @member {Array.<module:model/ContactoSolicitado>} data
 */
ContactoSolicitadoListResponse.prototype['data'] = undefined;






export default ContactoSolicitadoListResponse;

