/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactoSolicitadoInput model module.
 * @module model/ContactoSolicitadoInput
 * @version 1.0.0
 */
class ContactoSolicitadoInput {
    /**
     * Constructs a new <code>ContactoSolicitadoInput</code>.
     * @alias module:model/ContactoSolicitadoInput
     * @param empresaId {String} 
     * @param personaId {String} 
     */
    constructor(empresaId, personaId) { 
        
        ContactoSolicitadoInput.initialize(this, empresaId, personaId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, empresaId, personaId) { 
        obj['empresa_id'] = empresaId;
        obj['persona_id'] = personaId;
    }

    /**
     * Constructs a <code>ContactoSolicitadoInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactoSolicitadoInput} obj Optional instance to populate.
     * @return {module:model/ContactoSolicitadoInput} The populated <code>ContactoSolicitadoInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactoSolicitadoInput();

            if (data.hasOwnProperty('empresa_id')) {
                obj['empresa_id'] = ApiClient.convertToType(data['empresa_id'], 'String');
            }
            if (data.hasOwnProperty('persona_id')) {
                obj['persona_id'] = ApiClient.convertToType(data['persona_id'], 'String');
            }
            if (data.hasOwnProperty('notas_admin')) {
                obj['notas_admin'] = ApiClient.convertToType(data['notas_admin'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactoSolicitadoInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactoSolicitadoInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactoSolicitadoInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['empresa_id'] && !(typeof data['empresa_id'] === 'string' || data['empresa_id'] instanceof String)) {
            throw new Error("Expected the field `empresa_id` to be a primitive type in the JSON string but got " + data['empresa_id']);
        }
        // ensure the json data is a string
        if (data['persona_id'] && !(typeof data['persona_id'] === 'string' || data['persona_id'] instanceof String)) {
            throw new Error("Expected the field `persona_id` to be a primitive type in the JSON string but got " + data['persona_id']);
        }
        // ensure the json data is a string
        if (data['notas_admin'] && !(typeof data['notas_admin'] === 'string' || data['notas_admin'] instanceof String)) {
            throw new Error("Expected the field `notas_admin` to be a primitive type in the JSON string but got " + data['notas_admin']);
        }

        return true;
    }


}

ContactoSolicitadoInput.RequiredProperties = ["empresa_id", "persona_id"];

/**
 * @member {String} empresa_id
 */
ContactoSolicitadoInput.prototype['empresa_id'] = undefined;

/**
 * @member {String} persona_id
 */
ContactoSolicitadoInput.prototype['persona_id'] = undefined;

/**
 * @member {String} notas_admin
 */
ContactoSolicitadoInput.prototype['notas_admin'] = undefined;






export default ContactoSolicitadoInput;

