/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Empresa model module.
 * @module model/Empresa
 * @version 1.0.0
 */
class Empresa {
    /**
     * Constructs a new <code>Empresa</code>.
     * Modelo completo de empresa empleadora
     * @alias module:model/Empresa
     * @param nombreEmpresa {String} 
     * @param rutEmpresa {String} 
     * @param email {String} 
     * @param tipoEmpresa {module:model/Empresa.TipoEmpresaEnum} 
     * @param contactoNombre {String} 
     * @param contactoEmail {String} 
     */
    constructor(nombreEmpresa, rutEmpresa, email, tipoEmpresa, contactoNombre, contactoEmail) { 
        
        Empresa.initialize(this, nombreEmpresa, rutEmpresa, email, tipoEmpresa, contactoNombre, contactoEmail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nombreEmpresa, rutEmpresa, email, tipoEmpresa, contactoNombre, contactoEmail) { 
        obj['nombre_empresa'] = nombreEmpresa;
        obj['rut_empresa'] = rutEmpresa;
        obj['email'] = email;
        obj['tipo_empresa'] = tipoEmpresa;
        obj['contacto_nombre'] = contactoNombre;
        obj['contacto_email'] = contactoEmail;
    }

    /**
     * Constructs a <code>Empresa</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Empresa} obj Optional instance to populate.
     * @return {module:model/Empresa} The populated <code>Empresa</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Empresa();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nombre_empresa')) {
                obj['nombre_empresa'] = ApiClient.convertToType(data['nombre_empresa'], 'String');
            }
            if (data.hasOwnProperty('rut_empresa')) {
                obj['rut_empresa'] = ApiClient.convertToType(data['rut_empresa'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('logo_url')) {
                obj['logo_url'] = ApiClient.convertToType(data['logo_url'], 'String');
            }
            if (data.hasOwnProperty('rubro')) {
                obj['rubro'] = ApiClient.convertToType(data['rubro'], 'String');
            }
            if (data.hasOwnProperty('tipo_empresa')) {
                obj['tipo_empresa'] = ApiClient.convertToType(data['tipo_empresa'], 'String');
            }
            if (data.hasOwnProperty('presentacion')) {
                obj['presentacion'] = ApiClient.convertToType(data['presentacion'], 'String');
            }
            if (data.hasOwnProperty('beneficios')) {
                obj['beneficios'] = ApiClient.convertToType(data['beneficios'], ['String']);
            }
            if (data.hasOwnProperty('contacto_nombre')) {
                obj['contacto_nombre'] = ApiClient.convertToType(data['contacto_nombre'], 'String');
            }
            if (data.hasOwnProperty('contacto_email')) {
                obj['contacto_email'] = ApiClient.convertToType(data['contacto_email'], 'String');
            }
            if (data.hasOwnProperty('contacto_telefono')) {
                obj['contacto_telefono'] = ApiClient.convertToType(data['contacto_telefono'], 'String');
            }
            if (data.hasOwnProperty('validado')) {
                obj['validado'] = ApiClient.convertToType(data['validado'], 'Boolean');
            }
            if (data.hasOwnProperty('activo')) {
                obj['activo'] = ApiClient.convertToType(data['activo'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Empresa</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Empresa</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Empresa.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nombre_empresa'] && !(typeof data['nombre_empresa'] === 'string' || data['nombre_empresa'] instanceof String)) {
            throw new Error("Expected the field `nombre_empresa` to be a primitive type in the JSON string but got " + data['nombre_empresa']);
        }
        // ensure the json data is a string
        if (data['rut_empresa'] && !(typeof data['rut_empresa'] === 'string' || data['rut_empresa'] instanceof String)) {
            throw new Error("Expected the field `rut_empresa` to be a primitive type in the JSON string but got " + data['rut_empresa']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['logo_url'] && !(typeof data['logo_url'] === 'string' || data['logo_url'] instanceof String)) {
            throw new Error("Expected the field `logo_url` to be a primitive type in the JSON string but got " + data['logo_url']);
        }
        // ensure the json data is a string
        if (data['rubro'] && !(typeof data['rubro'] === 'string' || data['rubro'] instanceof String)) {
            throw new Error("Expected the field `rubro` to be a primitive type in the JSON string but got " + data['rubro']);
        }
        // ensure the json data is a string
        if (data['tipo_empresa'] && !(typeof data['tipo_empresa'] === 'string' || data['tipo_empresa'] instanceof String)) {
            throw new Error("Expected the field `tipo_empresa` to be a primitive type in the JSON string but got " + data['tipo_empresa']);
        }
        // ensure the json data is a string
        if (data['presentacion'] && !(typeof data['presentacion'] === 'string' || data['presentacion'] instanceof String)) {
            throw new Error("Expected the field `presentacion` to be a primitive type in the JSON string but got " + data['presentacion']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['beneficios'])) {
            throw new Error("Expected the field `beneficios` to be an array in the JSON data but got " + data['beneficios']);
        }
        // ensure the json data is a string
        if (data['contacto_nombre'] && !(typeof data['contacto_nombre'] === 'string' || data['contacto_nombre'] instanceof String)) {
            throw new Error("Expected the field `contacto_nombre` to be a primitive type in the JSON string but got " + data['contacto_nombre']);
        }
        // ensure the json data is a string
        if (data['contacto_email'] && !(typeof data['contacto_email'] === 'string' || data['contacto_email'] instanceof String)) {
            throw new Error("Expected the field `contacto_email` to be a primitive type in the JSON string but got " + data['contacto_email']);
        }
        // ensure the json data is a string
        if (data['contacto_telefono'] && !(typeof data['contacto_telefono'] === 'string' || data['contacto_telefono'] instanceof String)) {
            throw new Error("Expected the field `contacto_telefono` to be a primitive type in the JSON string but got " + data['contacto_telefono']);
        }

        return true;
    }


}

Empresa.RequiredProperties = ["nombre_empresa", "rut_empresa", "email", "tipo_empresa", "contacto_nombre", "contacto_email"];

/**
 * @member {String} id
 */
Empresa.prototype['id'] = undefined;

/**
 * @member {String} nombre_empresa
 */
Empresa.prototype['nombre_empresa'] = undefined;

/**
 * @member {String} rut_empresa
 */
Empresa.prototype['rut_empresa'] = undefined;

/**
 * @member {String} email
 */
Empresa.prototype['email'] = undefined;

/**
 * @member {String} logo_url
 */
Empresa.prototype['logo_url'] = undefined;

/**
 * @member {String} rubro
 */
Empresa.prototype['rubro'] = undefined;

/**
 * @member {module:model/Empresa.TipoEmpresaEnum} tipo_empresa
 */
Empresa.prototype['tipo_empresa'] = undefined;

/**
 * @member {String} presentacion
 */
Empresa.prototype['presentacion'] = undefined;

/**
 * @member {Array.<String>} beneficios
 */
Empresa.prototype['beneficios'] = undefined;

/**
 * @member {String} contacto_nombre
 */
Empresa.prototype['contacto_nombre'] = undefined;

/**
 * @member {String} contacto_email
 */
Empresa.prototype['contacto_email'] = undefined;

/**
 * @member {String} contacto_telefono
 */
Empresa.prototype['contacto_telefono'] = undefined;

/**
 * @member {Boolean} validado
 */
Empresa.prototype['validado'] = undefined;

/**
 * @member {Boolean} activo
 */
Empresa.prototype['activo'] = undefined;

/**
 * @member {Date} created_at
 */
Empresa.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Empresa.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>tipo_empresa</code> property.
 * @enum {String}
 * @readonly
 */
Empresa['TipoEmpresaEnum'] = {

    /**
     * value: "contratacion-directa"
     * @const
     */
    "contratacion-directa": "contratacion-directa",

    /**
     * value: "est"
     * @const
     */
    "est": "est",

    /**
     * value: "outsourcing"
     * @const
     */
    "outsourcing": "outsourcing"
};



export default Empresa;

