/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Empresa from './Empresa';

/**
 * The EmpresaValidationResult model module.
 * @module model/EmpresaValidationResult
 * @version 1.0.0
 */
class EmpresaValidationResult {
    /**
     * Constructs a new <code>EmpresaValidationResult</code>.
     * @alias module:model/EmpresaValidationResult
     * @param message {String} 
     * @param data {module:model/Empresa} 
     */
    constructor(message, data) { 
        
        EmpresaValidationResult.initialize(this, message, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, data) { 
        obj['message'] = message;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>EmpresaValidationResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmpresaValidationResult} obj Optional instance to populate.
     * @return {module:model/EmpresaValidationResult} The populated <code>EmpresaValidationResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmpresaValidationResult();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Empresa.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmpresaValidationResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmpresaValidationResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmpresaValidationResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          Empresa.validateJSON(data['data']);
        }

        return true;
    }


}

EmpresaValidationResult.RequiredProperties = ["message", "data"];

/**
 * @member {String} message
 */
EmpresaValidationResult.prototype['message'] = undefined;

/**
 * @member {module:model/Empresa} data
 */
EmpresaValidationResult.prototype['data'] = undefined;






export default EmpresaValidationResult;

