/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Estadisticas model module.
 * @module model/Estadisticas
 * @version 1.0.0
 */
class Estadisticas {
    /**
     * Constructs a new <code>Estadisticas</code>.
     * @alias module:model/Estadisticas
     * @param totalPersonas {Number} 
     * @param personasValidadas {Number} 
     * @param totalEmpresas {Number} 
     * @param empresasValidadas {Number} 
     * @param contactosPendientes {Number} 
     * @param contactosEnProceso {Number} 
     * @param contactosExitosos {Number} 
     */
    constructor(totalPersonas, personasValidadas, totalEmpresas, empresasValidadas, contactosPendientes, contactosEnProceso, contactosExitosos) { 
        
        Estadisticas.initialize(this, totalPersonas, personasValidadas, totalEmpresas, empresasValidadas, contactosPendientes, contactosEnProceso, contactosExitosos);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, totalPersonas, personasValidadas, totalEmpresas, empresasValidadas, contactosPendientes, contactosEnProceso, contactosExitosos) { 
        obj['total_personas'] = totalPersonas;
        obj['personas_validadas'] = personasValidadas;
        obj['total_empresas'] = totalEmpresas;
        obj['empresas_validadas'] = empresasValidadas;
        obj['contactos_pendientes'] = contactosPendientes;
        obj['contactos_en_proceso'] = contactosEnProceso;
        obj['contactos_exitosos'] = contactosExitosos;
    }

    /**
     * Constructs a <code>Estadisticas</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Estadisticas} obj Optional instance to populate.
     * @return {module:model/Estadisticas} The populated <code>Estadisticas</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Estadisticas();

            if (data.hasOwnProperty('total_personas')) {
                obj['total_personas'] = ApiClient.convertToType(data['total_personas'], 'Number');
            }
            if (data.hasOwnProperty('personas_validadas')) {
                obj['personas_validadas'] = ApiClient.convertToType(data['personas_validadas'], 'Number');
            }
            if (data.hasOwnProperty('total_empresas')) {
                obj['total_empresas'] = ApiClient.convertToType(data['total_empresas'], 'Number');
            }
            if (data.hasOwnProperty('empresas_validadas')) {
                obj['empresas_validadas'] = ApiClient.convertToType(data['empresas_validadas'], 'Number');
            }
            if (data.hasOwnProperty('contactos_pendientes')) {
                obj['contactos_pendientes'] = ApiClient.convertToType(data['contactos_pendientes'], 'Number');
            }
            if (data.hasOwnProperty('contactos_en_proceso')) {
                obj['contactos_en_proceso'] = ApiClient.convertToType(data['contactos_en_proceso'], 'Number');
            }
            if (data.hasOwnProperty('contactos_exitosos')) {
                obj['contactos_exitosos'] = ApiClient.convertToType(data['contactos_exitosos'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Estadisticas</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Estadisticas</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Estadisticas.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

Estadisticas.RequiredProperties = ["total_personas", "personas_validadas", "total_empresas", "empresas_validadas", "contactos_pendientes", "contactos_en_proceso", "contactos_exitosos"];

/**
 * @member {Number} total_personas
 */
Estadisticas.prototype['total_personas'] = undefined;

/**
 * @member {Number} personas_validadas
 */
Estadisticas.prototype['personas_validadas'] = undefined;

/**
 * @member {Number} total_empresas
 */
Estadisticas.prototype['total_empresas'] = undefined;

/**
 * @member {Number} empresas_validadas
 */
Estadisticas.prototype['empresas_validadas'] = undefined;

/**
 * @member {Number} contactos_pendientes
 */
Estadisticas.prototype['contactos_pendientes'] = undefined;

/**
 * @member {Number} contactos_en_proceso
 */
Estadisticas.prototype['contactos_en_proceso'] = undefined;

/**
 * @member {Number} contactos_exitosos
 */
Estadisticas.prototype['contactos_exitosos'] = undefined;






export default Estadisticas;

