/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Estadisticas from './Estadisticas';

/**
 * The EstadisticasResponse model module.
 * @module model/EstadisticasResponse
 * @version 1.0.0
 */
class EstadisticasResponse {
    /**
     * Constructs a new <code>EstadisticasResponse</code>.
     * @alias module:model/EstadisticasResponse
     * @param success {Boolean} 
     * @param data {module:model/Estadisticas} 
     */
    constructor(success, data) { 
        
        EstadisticasResponse.initialize(this, success, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, data) { 
        obj['success'] = success;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>EstadisticasResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EstadisticasResponse} obj Optional instance to populate.
     * @return {module:model/EstadisticasResponse} The populated <code>EstadisticasResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EstadisticasResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Estadisticas.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EstadisticasResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EstadisticasResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EstadisticasResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          Estadisticas.validateJSON(data['data']);
        }

        return true;
    }


}

EstadisticasResponse.RequiredProperties = ["success", "data"];

/**
 * @member {Boolean} success
 */
EstadisticasResponse.prototype['success'] = undefined;

/**
 * @member {module:model/Estadisticas} data
 */
EstadisticasResponse.prototype['data'] = undefined;






export default EstadisticasResponse;

