/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonaInput model module.
 * @module model/PersonaInput
 * @version 1.0.0
 */
class PersonaInput {
    /**
     * Constructs a new <code>PersonaInput</code>.
     * Datos para crear o actualizar una persona
     * @alias module:model/PersonaInput
     * @param email {String} 
     */
    constructor(email) { 
        
        PersonaInput.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>PersonaInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonaInput} obj Optional instance to populate.
     * @return {module:model/PersonaInput} The populated <code>PersonaInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonaInput();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('telefono')) {
                obj['telefono'] = ApiClient.convertToType(data['telefono'], 'String');
            }
            if (data.hasOwnProperty('resumen')) {
                obj['resumen'] = ApiClient.convertToType(data['resumen'], 'String');
            }
            if (data.hasOwnProperty('nivel_educacional')) {
                obj['nivel_educacional'] = ApiClient.convertToType(data['nivel_educacional'], 'String');
            }
            if (data.hasOwnProperty('titulo_carrera')) {
                obj['titulo_carrera'] = ApiClient.convertToType(data['titulo_carrera'], 'String');
            }
            if (data.hasOwnProperty('anio_egreso')) {
                obj['anio_egreso'] = ApiClient.convertToType(data['anio_egreso'], 'Number');
            }
            if (data.hasOwnProperty('anios_experiencia')) {
                obj['anios_experiencia'] = ApiClient.convertToType(data['anios_experiencia'], 'Number');
            }
            if (data.hasOwnProperty('areas_experiencia')) {
                obj['areas_experiencia'] = ApiClient.convertToType(data['areas_experiencia'], ['String']);
            }
            if (data.hasOwnProperty('competencias')) {
                obj['competencias'] = ApiClient.convertToType(data['competencias'], ['String']);
            }
            if (data.hasOwnProperty('rango_renta')) {
                obj['rango_renta'] = ApiClient.convertToType(data['rango_renta'], 'String');
            }
            if (data.hasOwnProperty('tipo_jornada')) {
                obj['tipo_jornada'] = ApiClient.convertToType(data['tipo_jornada'], 'String');
            }
            if (data.hasOwnProperty('modalidad')) {
                obj['modalidad'] = ApiClient.convertToType(data['modalidad'], 'String');
            }
            if (data.hasOwnProperty('persona_discapacidad')) {
                obj['persona_discapacidad'] = ApiClient.convertToType(data['persona_discapacidad'], 'Boolean');
            }
            if (data.hasOwnProperty('portafolio_url')) {
                obj['portafolio_url'] = ApiClient.convertToType(data['portafolio_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonaInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonaInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PersonaInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['telefono'] && !(typeof data['telefono'] === 'string' || data['telefono'] instanceof String)) {
            throw new Error("Expected the field `telefono` to be a primitive type in the JSON string but got " + data['telefono']);
        }
        // ensure the json data is a string
        if (data['resumen'] && !(typeof data['resumen'] === 'string' || data['resumen'] instanceof String)) {
            throw new Error("Expected the field `resumen` to be a primitive type in the JSON string but got " + data['resumen']);
        }
        // ensure the json data is a string
        if (data['nivel_educacional'] && !(typeof data['nivel_educacional'] === 'string' || data['nivel_educacional'] instanceof String)) {
            throw new Error("Expected the field `nivel_educacional` to be a primitive type in the JSON string but got " + data['nivel_educacional']);
        }
        // ensure the json data is a string
        if (data['titulo_carrera'] && !(typeof data['titulo_carrera'] === 'string' || data['titulo_carrera'] instanceof String)) {
            throw new Error("Expected the field `titulo_carrera` to be a primitive type in the JSON string but got " + data['titulo_carrera']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['areas_experiencia'])) {
            throw new Error("Expected the field `areas_experiencia` to be an array in the JSON data but got " + data['areas_experiencia']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['competencias'])) {
            throw new Error("Expected the field `competencias` to be an array in the JSON data but got " + data['competencias']);
        }
        // ensure the json data is a string
        if (data['rango_renta'] && !(typeof data['rango_renta'] === 'string' || data['rango_renta'] instanceof String)) {
            throw new Error("Expected the field `rango_renta` to be a primitive type in the JSON string but got " + data['rango_renta']);
        }
        // ensure the json data is a string
        if (data['tipo_jornada'] && !(typeof data['tipo_jornada'] === 'string' || data['tipo_jornada'] instanceof String)) {
            throw new Error("Expected the field `tipo_jornada` to be a primitive type in the JSON string but got " + data['tipo_jornada']);
        }
        // ensure the json data is a string
        if (data['modalidad'] && !(typeof data['modalidad'] === 'string' || data['modalidad'] instanceof String)) {
            throw new Error("Expected the field `modalidad` to be a primitive type in the JSON string but got " + data['modalidad']);
        }
        // ensure the json data is a string
        if (data['portafolio_url'] && !(typeof data['portafolio_url'] === 'string' || data['portafolio_url'] instanceof String)) {
            throw new Error("Expected the field `portafolio_url` to be a primitive type in the JSON string but got " + data['portafolio_url']);
        }

        return true;
    }


}

PersonaInput.RequiredProperties = ["email"];

/**
 * @member {String} email
 */
PersonaInput.prototype['email'] = undefined;

/**
 * @member {String} telefono
 */
PersonaInput.prototype['telefono'] = undefined;

/**
 * @member {String} resumen
 */
PersonaInput.prototype['resumen'] = undefined;

/**
 * @member {module:model/PersonaInput.NivelEducacionalEnum} nivel_educacional
 */
PersonaInput.prototype['nivel_educacional'] = undefined;

/**
 * @member {String} titulo_carrera
 */
PersonaInput.prototype['titulo_carrera'] = undefined;

/**
 * @member {Number} anio_egreso
 */
PersonaInput.prototype['anio_egreso'] = undefined;

/**
 * @member {Number} anios_experiencia
 */
PersonaInput.prototype['anios_experiencia'] = undefined;

/**
 * @member {Array.<String>} areas_experiencia
 */
PersonaInput.prototype['areas_experiencia'] = undefined;

/**
 * @member {Array.<String>} competencias
 */
PersonaInput.prototype['competencias'] = undefined;

/**
 * @member {String} rango_renta
 */
PersonaInput.prototype['rango_renta'] = undefined;

/**
 * @member {module:model/PersonaInput.TipoJornadaEnum} tipo_jornada
 */
PersonaInput.prototype['tipo_jornada'] = undefined;

/**
 * @member {module:model/PersonaInput.ModalidadEnum} modalidad
 */
PersonaInput.prototype['modalidad'] = undefined;

/**
 * @member {Boolean} persona_discapacidad
 */
PersonaInput.prototype['persona_discapacidad'] = undefined;

/**
 * @member {String} portafolio_url
 */
PersonaInput.prototype['portafolio_url'] = undefined;





/**
 * Allowed values for the <code>nivel_educacional</code> property.
 * @enum {String}
 * @readonly
 */
PersonaInput['NivelEducacionalEnum'] = {

    /**
     * value: "basica"
     * @const
     */
    "basica": "basica",

    /**
     * value: "media"
     * @const
     */
    "media": "media",

    /**
     * value: "tecnica"
     * @const
     */
    "tecnica": "tecnica",

    /**
     * value: "universitaria"
     * @const
     */
    "universitaria": "universitaria",

    /**
     * value: "postgrado"
     * @const
     */
    "postgrado": "postgrado"
};


/**
 * Allowed values for the <code>tipo_jornada</code> property.
 * @enum {String}
 * @readonly
 */
PersonaInput['TipoJornadaEnum'] = {

    /**
     * value: "completa"
     * @const
     */
    "completa": "completa",

    /**
     * value: "part-time"
     * @const
     */
    "part-time": "part-time",

    /**
     * value: "por-horas"
     * @const
     */
    "por-horas": "por-horas"
};


/**
 * Allowed values for the <code>modalidad</code> property.
 * @enum {String}
 * @readonly
 */
PersonaInput['ModalidadEnum'] = {

    /**
     * value: "presencial"
     * @const
     */
    "presencial": "presencial",

    /**
     * value: "remoto"
     * @const
     */
    "remoto": "remoto",

    /**
     * value: "hibrido"
     * @const
     */
    "hibrido": "hibrido"
};



export default PersonaInput;

