/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Persona from './Persona';

/**
 * The PersonaValidationResult model module.
 * @module model/PersonaValidationResult
 * @version 1.0.0
 */
class PersonaValidationResult {
    /**
     * Constructs a new <code>PersonaValidationResult</code>.
     * @alias module:model/PersonaValidationResult
     * @param message {String} 
     * @param data {module:model/Persona} 
     */
    constructor(message, data) { 
        
        PersonaValidationResult.initialize(this, message, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, data) { 
        obj['message'] = message;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>PersonaValidationResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonaValidationResult} obj Optional instance to populate.
     * @return {module:model/PersonaValidationResult} The populated <code>PersonaValidationResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonaValidationResult();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Persona.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonaValidationResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonaValidationResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PersonaValidationResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          Persona.validateJSON(data['data']);
        }

        return true;
    }


}

PersonaValidationResult.RequiredProperties = ["message", "data"];

/**
 * @member {String} message
 */
PersonaValidationResult.prototype['message'] = undefined;

/**
 * @member {module:model/Persona} data
 */
PersonaValidationResult.prototype['data'] = undefined;






export default PersonaValidationResult;

