/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonaIdiomasInner model module.
 * @module model/PersonaIdiomasInner
 * @version 1.0.0
 */
class PersonaIdiomasInner {
    /**
     * Constructs a new <code>PersonaIdiomasInner</code>.
     * @alias module:model/PersonaIdiomasInner
     */
    constructor() { 
        
        PersonaIdiomasInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonaIdiomasInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonaIdiomasInner} obj Optional instance to populate.
     * @return {module:model/PersonaIdiomasInner} The populated <code>PersonaIdiomasInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonaIdiomasInner();

            if (data.hasOwnProperty('idioma')) {
                obj['idioma'] = ApiClient.convertToType(data['idioma'], 'String');
            }
            if (data.hasOwnProperty('nivel')) {
                obj['nivel'] = ApiClient.convertToType(data['nivel'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonaIdiomasInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonaIdiomasInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['idioma'] && !(typeof data['idioma'] === 'string' || data['idioma'] instanceof String)) {
            throw new Error("Expected the field `idioma` to be a primitive type in the JSON string but got " + data['idioma']);
        }
        // ensure the json data is a string
        if (data['nivel'] && !(typeof data['nivel'] === 'string' || data['nivel'] instanceof String)) {
            throw new Error("Expected the field `nivel` to be a primitive type in the JSON string but got " + data['nivel']);
        }

        return true;
    }


}



/**
 * @member {String} idioma
 */
PersonaIdiomasInner.prototype['idioma'] = undefined;

/**
 * @member {module:model/PersonaIdiomasInner.NivelEnum} nivel
 */
PersonaIdiomasInner.prototype['nivel'] = undefined;





/**
 * Allowed values for the <code>nivel</code> property.
 * @enum {String}
 * @readonly
 */
PersonaIdiomasInner['NivelEnum'] = {

    /**
     * value: "basico"
     * @const
     */
    "basico": "basico",

    /**
     * value: "intermedio"
     * @const
     */
    "intermedio": "intermedio",

    /**
     * value: "avanzado"
     * @const
     */
    "avanzado": "avanzado",

    /**
     * value: "nativo"
     * @const
     */
    "nativo": "nativo"
};



export default PersonaIdiomasInner;

