/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonaCursosInner model module.
 * @module model/PersonaCursosInner
 * @version 1.0.0
 */
class PersonaCursosInner {
    /**
     * Constructs a new <code>PersonaCursosInner</code>.
     * @alias module:model/PersonaCursosInner
     */
    constructor() { 
        
        PersonaCursosInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonaCursosInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonaCursosInner} obj Optional instance to populate.
     * @return {module:model/PersonaCursosInner} The populated <code>PersonaCursosInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonaCursosInner();

            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('institucion')) {
                obj['institucion'] = ApiClient.convertToType(data['institucion'], 'String');
            }
            if (data.hasOwnProperty('anio')) {
                obj['anio'] = ApiClient.convertToType(data['anio'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonaCursosInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonaCursosInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['institucion'] && !(typeof data['institucion'] === 'string' || data['institucion'] instanceof String)) {
            throw new Error("Expected the field `institucion` to be a primitive type in the JSON string but got " + data['institucion']);
        }

        return true;
    }


}



/**
 * @member {String} nombre
 */
PersonaCursosInner.prototype['nombre'] = undefined;

/**
 * @member {String} institucion
 */
PersonaCursosInner.prototype['institucion'] = undefined;

/**
 * @member {Number} anio
 */
PersonaCursosInner.prototype['anio'] = undefined;






export default PersonaCursosInner;

