/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonaCVCiego model module.
 * @module model/PersonaCVCiego
 * @version 1.0.0
 */
class PersonaCVCiego {
    /**
     * Constructs a new <code>PersonaCVCiego</code>.
     * Vista pública del talento sin datos personales identificables
     * @alias module:model/PersonaCVCiego
     */
    constructor() { 
        
        PersonaCVCiego.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonaCVCiego</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonaCVCiego} obj Optional instance to populate.
     * @return {module:model/PersonaCVCiego} The populated <code>PersonaCVCiego</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonaCVCiego();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('codigo_talento')) {
                obj['codigo_talento'] = ApiClient.convertToType(data['codigo_talento'], 'String');
            }
            if (data.hasOwnProperty('resumen')) {
                obj['resumen'] = ApiClient.convertToType(data['resumen'], 'String');
            }
            if (data.hasOwnProperty('nivel_educacional')) {
                obj['nivel_educacional'] = ApiClient.convertToType(data['nivel_educacional'], 'String');
            }
            if (data.hasOwnProperty('titulo_carrera')) {
                obj['titulo_carrera'] = ApiClient.convertToType(data['titulo_carrera'], 'String');
            }
            if (data.hasOwnProperty('anio_egreso')) {
                obj['anio_egreso'] = ApiClient.convertToType(data['anio_egreso'], 'Number');
            }
            if (data.hasOwnProperty('anios_experiencia')) {
                obj['anios_experiencia'] = ApiClient.convertToType(data['anios_experiencia'], 'Number');
            }
            if (data.hasOwnProperty('tipo_jornada')) {
                obj['tipo_jornada'] = ApiClient.convertToType(data['tipo_jornada'], 'String');
            }
            if (data.hasOwnProperty('modalidad')) {
                obj['modalidad'] = ApiClient.convertToType(data['modalidad'], 'String');
            }
            if (data.hasOwnProperty('persona_discapacidad')) {
                obj['persona_discapacidad'] = ApiClient.convertToType(data['persona_discapacidad'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonaCVCiego</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonaCVCiego</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['codigo_talento'] && !(typeof data['codigo_talento'] === 'string' || data['codigo_talento'] instanceof String)) {
            throw new Error("Expected the field `codigo_talento` to be a primitive type in the JSON string but got " + data['codigo_talento']);
        }
        // ensure the json data is a string
        if (data['resumen'] && !(typeof data['resumen'] === 'string' || data['resumen'] instanceof String)) {
            throw new Error("Expected the field `resumen` to be a primitive type in the JSON string but got " + data['resumen']);
        }
        // ensure the json data is a string
        if (data['nivel_educacional'] && !(typeof data['nivel_educacional'] === 'string' || data['nivel_educacional'] instanceof String)) {
            throw new Error("Expected the field `nivel_educacional` to be a primitive type in the JSON string but got " + data['nivel_educacional']);
        }
        // ensure the json data is a string
        if (data['titulo_carrera'] && !(typeof data['titulo_carrera'] === 'string' || data['titulo_carrera'] instanceof String)) {
            throw new Error("Expected the field `titulo_carrera` to be a primitive type in the JSON string but got " + data['titulo_carrera']);
        }
        // ensure the json data is a string
        if (data['tipo_jornada'] && !(typeof data['tipo_jornada'] === 'string' || data['tipo_jornada'] instanceof String)) {
            throw new Error("Expected the field `tipo_jornada` to be a primitive type in the JSON string but got " + data['tipo_jornada']);
        }
        // ensure the json data is a string
        if (data['modalidad'] && !(typeof data['modalidad'] === 'string' || data['modalidad'] instanceof String)) {
            throw new Error("Expected the field `modalidad` to be a primitive type in the JSON string but got " + data['modalidad']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PersonaCVCiego.prototype['id'] = undefined;

/**
 * @member {String} codigo_talento
 */
PersonaCVCiego.prototype['codigo_talento'] = undefined;

/**
 * @member {String} resumen
 */
PersonaCVCiego.prototype['resumen'] = undefined;

/**
 * @member {String} nivel_educacional
 */
PersonaCVCiego.prototype['nivel_educacional'] = undefined;

/**
 * @member {String} titulo_carrera
 */
PersonaCVCiego.prototype['titulo_carrera'] = undefined;

/**
 * @member {Number} anio_egreso
 */
PersonaCVCiego.prototype['anio_egreso'] = undefined;

/**
 * @member {Number} anios_experiencia
 */
PersonaCVCiego.prototype['anios_experiencia'] = undefined;

/**
 * @member {String} tipo_jornada
 */
PersonaCVCiego.prototype['tipo_jornada'] = undefined;

/**
 * @member {String} modalidad
 */
PersonaCVCiego.prototype['modalidad'] = undefined;

/**
 * @member {Boolean} persona_discapacidad
 */
PersonaCVCiego.prototype['persona_discapacidad'] = undefined;






export default PersonaCVCiego;

