/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PersonaCursosInner from './PersonaCursosInner';
import PersonaIdiomasInner from './PersonaIdiomasInner';

/**
 * The Persona model module.
 * @module model/Persona
 * @version 1.0.0
 */
class Persona {
    /**
     * Constructs a new <code>Persona</code>.
     * Modelo completo de persona/talento
     * @alias module:model/Persona
     * @param email {String} 
     * @param codigoTalento {String} 
     */
    constructor(email, codigoTalento) { 
        
        Persona.initialize(this, email, codigoTalento);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, codigoTalento) { 
        obj['email'] = email;
        obj['codigo_talento'] = codigoTalento;
    }

    /**
     * Constructs a <code>Persona</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Persona} obj Optional instance to populate.
     * @return {module:model/Persona} The populated <code>Persona</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Persona();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('telefono')) {
                obj['telefono'] = ApiClient.convertToType(data['telefono'], 'String');
            }
            if (data.hasOwnProperty('codigo_talento')) {
                obj['codigo_talento'] = ApiClient.convertToType(data['codigo_talento'], 'String');
            }
            if (data.hasOwnProperty('resumen')) {
                obj['resumen'] = ApiClient.convertToType(data['resumen'], 'String');
            }
            if (data.hasOwnProperty('nivel_educacional')) {
                obj['nivel_educacional'] = ApiClient.convertToType(data['nivel_educacional'], 'String');
            }
            if (data.hasOwnProperty('titulo_carrera')) {
                obj['titulo_carrera'] = ApiClient.convertToType(data['titulo_carrera'], 'String');
            }
            if (data.hasOwnProperty('anio_egreso')) {
                obj['anio_egreso'] = ApiClient.convertToType(data['anio_egreso'], 'Number');
            }
            if (data.hasOwnProperty('anios_experiencia')) {
                obj['anios_experiencia'] = ApiClient.convertToType(data['anios_experiencia'], 'Number');
            }
            if (data.hasOwnProperty('areas_experiencia')) {
                obj['areas_experiencia'] = ApiClient.convertToType(data['areas_experiencia'], ['String']);
            }
            if (data.hasOwnProperty('competencias')) {
                obj['competencias'] = ApiClient.convertToType(data['competencias'], ['String']);
            }
            if (data.hasOwnProperty('rango_renta')) {
                obj['rango_renta'] = ApiClient.convertToType(data['rango_renta'], 'String');
            }
            if (data.hasOwnProperty('tipo_jornada')) {
                obj['tipo_jornada'] = ApiClient.convertToType(data['tipo_jornada'], 'String');
            }
            if (data.hasOwnProperty('modalidad')) {
                obj['modalidad'] = ApiClient.convertToType(data['modalidad'], 'String');
            }
            if (data.hasOwnProperty('cursos')) {
                obj['cursos'] = ApiClient.convertToType(data['cursos'], [PersonaCursosInner]);
            }
            if (data.hasOwnProperty('idiomas')) {
                obj['idiomas'] = ApiClient.convertToType(data['idiomas'], [PersonaIdiomasInner]);
            }
            if (data.hasOwnProperty('portafolio_url')) {
                obj['portafolio_url'] = ApiClient.convertToType(data['portafolio_url'], 'String');
            }
            if (data.hasOwnProperty('persona_discapacidad')) {
                obj['persona_discapacidad'] = ApiClient.convertToType(data['persona_discapacidad'], 'Boolean');
            }
            if (data.hasOwnProperty('validado')) {
                obj['validado'] = ApiClient.convertToType(data['validado'], 'Boolean');
            }
            if (data.hasOwnProperty('activo')) {
                obj['activo'] = ApiClient.convertToType(data['activo'], 'Boolean');
            }
            if (data.hasOwnProperty('porcentaje_completitud')) {
                obj['porcentaje_completitud'] = ApiClient.convertToType(data['porcentaje_completitud'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Persona</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Persona</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Persona.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['telefono'] && !(typeof data['telefono'] === 'string' || data['telefono'] instanceof String)) {
            throw new Error("Expected the field `telefono` to be a primitive type in the JSON string but got " + data['telefono']);
        }
        // ensure the json data is a string
        if (data['codigo_talento'] && !(typeof data['codigo_talento'] === 'string' || data['codigo_talento'] instanceof String)) {
            throw new Error("Expected the field `codigo_talento` to be a primitive type in the JSON string but got " + data['codigo_talento']);
        }
        // ensure the json data is a string
        if (data['resumen'] && !(typeof data['resumen'] === 'string' || data['resumen'] instanceof String)) {
            throw new Error("Expected the field `resumen` to be a primitive type in the JSON string but got " + data['resumen']);
        }
        // ensure the json data is a string
        if (data['nivel_educacional'] && !(typeof data['nivel_educacional'] === 'string' || data['nivel_educacional'] instanceof String)) {
            throw new Error("Expected the field `nivel_educacional` to be a primitive type in the JSON string but got " + data['nivel_educacional']);
        }
        // ensure the json data is a string
        if (data['titulo_carrera'] && !(typeof data['titulo_carrera'] === 'string' || data['titulo_carrera'] instanceof String)) {
            throw new Error("Expected the field `titulo_carrera` to be a primitive type in the JSON string but got " + data['titulo_carrera']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['areas_experiencia'])) {
            throw new Error("Expected the field `areas_experiencia` to be an array in the JSON data but got " + data['areas_experiencia']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['competencias'])) {
            throw new Error("Expected the field `competencias` to be an array in the JSON data but got " + data['competencias']);
        }
        // ensure the json data is a string
        if (data['rango_renta'] && !(typeof data['rango_renta'] === 'string' || data['rango_renta'] instanceof String)) {
            throw new Error("Expected the field `rango_renta` to be a primitive type in the JSON string but got " + data['rango_renta']);
        }
        // ensure the json data is a string
        if (data['tipo_jornada'] && !(typeof data['tipo_jornada'] === 'string' || data['tipo_jornada'] instanceof String)) {
            throw new Error("Expected the field `tipo_jornada` to be a primitive type in the JSON string but got " + data['tipo_jornada']);
        }
        // ensure the json data is a string
        if (data['modalidad'] && !(typeof data['modalidad'] === 'string' || data['modalidad'] instanceof String)) {
            throw new Error("Expected the field `modalidad` to be a primitive type in the JSON string but got " + data['modalidad']);
        }
        if (data['cursos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cursos'])) {
                throw new Error("Expected the field `cursos` to be an array in the JSON data but got " + data['cursos']);
            }
            // validate the optional field `cursos` (array)
            for (const item of data['cursos']) {
                PersonaCursosInner.validateJSON(item);
            };
        }
        if (data['idiomas']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['idiomas'])) {
                throw new Error("Expected the field `idiomas` to be an array in the JSON data but got " + data['idiomas']);
            }
            // validate the optional field `idiomas` (array)
            for (const item of data['idiomas']) {
                PersonaIdiomasInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['portafolio_url'] && !(typeof data['portafolio_url'] === 'string' || data['portafolio_url'] instanceof String)) {
            throw new Error("Expected the field `portafolio_url` to be a primitive type in the JSON string but got " + data['portafolio_url']);
        }

        return true;
    }


}

Persona.RequiredProperties = ["email", "codigo_talento"];

/**
 * @member {String} id
 */
Persona.prototype['id'] = undefined;

/**
 * @member {String} email
 */
Persona.prototype['email'] = undefined;

/**
 * @member {String} telefono
 */
Persona.prototype['telefono'] = undefined;

/**
 * @member {String} codigo_talento
 */
Persona.prototype['codigo_talento'] = undefined;

/**
 * @member {String} resumen
 */
Persona.prototype['resumen'] = undefined;

/**
 * @member {module:model/Persona.NivelEducacionalEnum} nivel_educacional
 */
Persona.prototype['nivel_educacional'] = undefined;

/**
 * @member {String} titulo_carrera
 */
Persona.prototype['titulo_carrera'] = undefined;

/**
 * @member {Number} anio_egreso
 */
Persona.prototype['anio_egreso'] = undefined;

/**
 * @member {Number} anios_experiencia
 */
Persona.prototype['anios_experiencia'] = undefined;

/**
 * @member {Array.<String>} areas_experiencia
 */
Persona.prototype['areas_experiencia'] = undefined;

/**
 * @member {Array.<String>} competencias
 */
Persona.prototype['competencias'] = undefined;

/**
 * @member {String} rango_renta
 */
Persona.prototype['rango_renta'] = undefined;

/**
 * @member {module:model/Persona.TipoJornadaEnum} tipo_jornada
 */
Persona.prototype['tipo_jornada'] = undefined;

/**
 * @member {module:model/Persona.ModalidadEnum} modalidad
 */
Persona.prototype['modalidad'] = undefined;

/**
 * @member {Array.<module:model/PersonaCursosInner>} cursos
 */
Persona.prototype['cursos'] = undefined;

/**
 * @member {Array.<module:model/PersonaIdiomasInner>} idiomas
 */
Persona.prototype['idiomas'] = undefined;

/**
 * @member {String} portafolio_url
 */
Persona.prototype['portafolio_url'] = undefined;

/**
 * @member {Boolean} persona_discapacidad
 */
Persona.prototype['persona_discapacidad'] = undefined;

/**
 * @member {Boolean} validado
 */
Persona.prototype['validado'] = undefined;

/**
 * @member {Boolean} activo
 */
Persona.prototype['activo'] = undefined;

/**
 * @member {Number} porcentaje_completitud
 */
Persona.prototype['porcentaje_completitud'] = undefined;

/**
 * @member {Date} created_at
 */
Persona.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Persona.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>nivel_educacional</code> property.
 * @enum {String}
 * @readonly
 */
Persona['NivelEducacionalEnum'] = {

    /**
     * value: "basica"
     * @const
     */
    "basica": "basica",

    /**
     * value: "media"
     * @const
     */
    "media": "media",

    /**
     * value: "tecnica"
     * @const
     */
    "tecnica": "tecnica",

    /**
     * value: "universitaria"
     * @const
     */
    "universitaria": "universitaria",

    /**
     * value: "postgrado"
     * @const
     */
    "postgrado": "postgrado"
};


/**
 * Allowed values for the <code>tipo_jornada</code> property.
 * @enum {String}
 * @readonly
 */
Persona['TipoJornadaEnum'] = {

    /**
     * value: "completa"
     * @const
     */
    "completa": "completa",

    /**
     * value: "part-time"
     * @const
     */
    "part-time": "part-time",

    /**
     * value: "por-horas"
     * @const
     */
    "por-horas": "por-horas"
};


/**
 * Allowed values for the <code>modalidad</code> property.
 * @enum {String}
 * @readonly
 */
Persona['ModalidadEnum'] = {

    /**
     * value: "presencial"
     * @const
     */
    "presencial": "presencial",

    /**
     * value: "remoto"
     * @const
     */
    "remoto": "remoto",

    /**
     * value: "hibrido"
     * @const
     */
    "hibrido": "hibrido"
};



export default Persona;

