/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ActualizarEstadoContactoRequest from '../model/ActualizarEstadoContactoRequest';
import ContactoSolicitadoInput from '../model/ContactoSolicitadoInput';
import ContactoSolicitadoListResponse from '../model/ContactoSolicitadoListResponse';
import ContactoSolicitadoResponse from '../model/ContactoSolicitadoResponse';
import ErrorResponse from '../model/ErrorResponse';
import EstadisticasResponse from '../model/EstadisticasResponse';

/**
* Administracin service.
* @module api/AdministracinApi
* @version 1.0.0
*/
export default class AdministracinApi {

    /**
    * Constructs a new AdministracinApi. 
    * @alias module:api/AdministracinApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the actualizarEstadoContacto operation.
     * @callback module:api/AdministracinApi~actualizarEstadoContactoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContactoSolicitadoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Actualizar estado de contacto
     * Cambia el estado del proceso. Las fechas se registran automáticamente según el estado. Rate limit: 20 solicitudes por minuto por IP.
     * @param {String} contacto 
     * @param {module:model/ActualizarEstadoContactoRequest} actualizarEstadoContactoRequest 
     * @param {module:api/AdministracinApi~actualizarEstadoContactoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContactoSolicitadoResponse}
     */
    actualizarEstadoContacto(contacto, actualizarEstadoContactoRequest, callback) {
      let postBody = actualizarEstadoContactoRequest;
      // verify the required parameter 'contacto' is set
      if (contacto === undefined || contacto === null) {
        throw new Error("Missing the required parameter 'contacto' when calling actualizarEstadoContacto");
      }
      // verify the required parameter 'actualizarEstadoContactoRequest' is set
      if (actualizarEstadoContactoRequest === undefined || actualizarEstadoContactoRequest === null) {
        throw new Error("Missing the required parameter 'actualizarEstadoContactoRequest' when calling actualizarEstadoContacto");
      }

      let pathParams = {
        'contacto': contacto
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ContactoSolicitadoResponse;
      return this.apiClient.callApi(
        '/admin/contactos/{contacto}/estado', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the crearContactoSolicitado operation.
     * @callback module:api/AdministracinApi~crearContactoSolicitadoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContactoSolicitadoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Registrar solicitud de contacto
     * Una empresa solicita contactar a un talento. No puede existir una solicitud activa previa. Rate limit: 20 solicitudes por minuto por IP.
     * @param {module:model/ContactoSolicitadoInput} contactoSolicitadoInput 
     * @param {module:api/AdministracinApi~crearContactoSolicitadoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContactoSolicitadoResponse}
     */
    crearContactoSolicitado(contactoSolicitadoInput, callback) {
      let postBody = contactoSolicitadoInput;
      // verify the required parameter 'contactoSolicitadoInput' is set
      if (contactoSolicitadoInput === undefined || contactoSolicitadoInput === null) {
        throw new Error("Missing the required parameter 'contactoSolicitadoInput' when calling crearContactoSolicitado");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ContactoSolicitadoResponse;
      return this.apiClient.callApi(
        '/admin/contactos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getContactosSolicitados operation.
     * @callback module:api/AdministracinApi~getContactosSolicitadosCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContactoSolicitadoListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Listar contactos solicitados
     * Consulta administrativa de lectura. Rate limit: 60 solicitudes por minuto por IP.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [estado] 
     * @param {module:api/AdministracinApi~getContactosSolicitadosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContactoSolicitadoListResponse}
     */
    getContactosSolicitados(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'estado': opts['estado']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ContactoSolicitadoListResponse;
      return this.apiClient.callApi(
        '/admin/contactos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getEstadisticas operation.
     * @callback module:api/AdministracinApi~getEstadisticasCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EstadisticasResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Estadísticas generales de la plataforma
     * Dashboard resumido de la plataforma. Rate limit: 60 solicitudes por minuto por IP. Respuesta con Cache-Control de 30 segundos por tratarse de métricas agregadas.
     * @param {module:api/AdministracinApi~getEstadisticasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EstadisticasResponse}
     */
    getEstadisticas(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EstadisticasResponse;
      return this.apiClient.callApi(
        '/admin/estadisticas', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
