/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EmpresaInput from '../model/EmpresaInput';
import EmpresaListResponse from '../model/EmpresaListResponse';
import EmpresaResponse from '../model/EmpresaResponse';
import EmpresaValidationResponse from '../model/EmpresaValidationResponse';
import ErrorResponse from '../model/ErrorResponse';
import MessageResponse from '../model/MessageResponse';

/**
* Empresas service.
* @module api/EmpresasApi
* @version 1.0.0
*/
export default class EmpresasApi {

    /**
    * Constructs a new EmpresasApi. 
    * @alias module:api/EmpresasApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createEmpresa operation.
     * @callback module:api/EmpresasApi~createEmpresaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmpresaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Registrar nueva empresa
     * @param {module:model/EmpresaInput} empresaInput 
     * @param {module:api/EmpresasApi~createEmpresaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmpresaResponse}
     */
    createEmpresa(empresaInput, callback) {
      let postBody = empresaInput;
      // verify the required parameter 'empresaInput' is set
      if (empresaInput === undefined || empresaInput === null) {
        throw new Error("Missing the required parameter 'empresaInput' when calling createEmpresa");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EmpresaResponse;
      return this.apiClient.callApi(
        '/empresas', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteEmpresa operation.
     * @callback module:api/EmpresasApi~deleteEmpresaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Desactivar empresa
     * Desactiva el perfil sin eliminarlo de la base de datos. Rate limit: 30 solicitudes por minuto por IP.
     * @param {String} empresa 
     * @param {module:api/EmpresasApi~deleteEmpresaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageResponse}
     */
    deleteEmpresa(empresa, callback) {
      let postBody = null;
      // verify the required parameter 'empresa' is set
      if (empresa === undefined || empresa === null) {
        throw new Error("Missing the required parameter 'empresa' when calling deleteEmpresa");
      }

      let pathParams = {
        'empresa': empresa
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageResponse;
      return this.apiClient.callApi(
        '/empresas/{empresa}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getEmpresa operation.
     * @callback module:api/EmpresasApi~getEmpresaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmpresaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener empresa por ID
     * Consulta de lectura con rate limit de 120 solicitudes por minuto por IP.
     * @param {String} empresa 
     * @param {module:api/EmpresasApi~getEmpresaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmpresaResponse}
     */
    getEmpresa(empresa, callback) {
      let postBody = null;
      // verify the required parameter 'empresa' is set
      if (empresa === undefined || empresa === null) {
        throw new Error("Missing the required parameter 'empresa' when calling getEmpresa");
      }

      let pathParams = {
        'empresa': empresa
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmpresaResponse;
      return this.apiClient.callApi(
        '/empresas/{empresa}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getEmpresas operation.
     * @callback module:api/EmpresasApi~getEmpresasCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmpresaListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Listar empresas validadas
     * Obtiene empresas activas. Rate limit: 120 solicitudes por minuto por IP. Se recomienda filtrar por tipo cuando se integre desde clientes externos.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [tipoEmpresa] 
     * @param {module:api/EmpresasApi~getEmpresasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmpresaListResponse}
     */
    getEmpresas(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'tipo_empresa': opts['tipoEmpresa']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmpresaListResponse;
      return this.apiClient.callApi(
        '/empresas', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateEmpresa operation.
     * @callback module:api/EmpresasApi~updateEmpresaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmpresaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Actualizar empresa
     * @param {String} empresa 
     * @param {module:model/EmpresaInput} empresaInput 
     * @param {module:api/EmpresasApi~updateEmpresaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmpresaResponse}
     */
    updateEmpresa(empresa, empresaInput, callback) {
      let postBody = empresaInput;
      // verify the required parameter 'empresa' is set
      if (empresa === undefined || empresa === null) {
        throw new Error("Missing the required parameter 'empresa' when calling updateEmpresa");
      }
      // verify the required parameter 'empresaInput' is set
      if (empresaInput === undefined || empresaInput === null) {
        throw new Error("Missing the required parameter 'empresaInput' when calling updateEmpresa");
      }

      let pathParams = {
        'empresa': empresa
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EmpresaResponse;
      return this.apiClient.callApi(
        '/empresas/{empresa}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the validarEmpresa operation.
     * @callback module:api/EmpresasApi~validarEmpresaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmpresaValidationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validar empresa (solo administración)
     * Marca una empresa como validada. Rate limit: 30 solicitudes por minuto por IP.
     * @param {String} empresa 
     * @param {module:api/EmpresasApi~validarEmpresaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmpresaValidationResponse}
     */
    validarEmpresa(empresa, callback) {
      let postBody = null;
      // verify the required parameter 'empresa' is set
      if (empresa === undefined || empresa === null) {
        throw new Error("Missing the required parameter 'empresa' when calling validarEmpresa");
      }

      let pathParams = {
        'empresa': empresa
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmpresaValidationResponse;
      return this.apiClient.callApi(
        '/empresas/{empresa}/validar', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
