/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import MessageResponse from '../model/MessageResponse';
import PersonaInput from '../model/PersonaInput';
import PersonaListResponse from '../model/PersonaListResponse';
import PersonaResponse from '../model/PersonaResponse';
import PersonaValidationResponse from '../model/PersonaValidationResponse';

/**
* Personas service.
* @module api/PersonasApi
* @version 1.0.0
*/
export default class PersonasApi {

    /**
    * Constructs a new PersonasApi. 
    * @alias module:api/PersonasApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createPersona operation.
     * @callback module:api/PersonasApi~createPersonaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Registrar nueva persona/talento
     * Crea un perfil de talento. El código se genera automáticamente.
     * @param {module:model/PersonaInput} personaInput 
     * @param {module:api/PersonasApi~createPersonaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonaResponse}
     */
    createPersona(personaInput, callback) {
      let postBody = personaInput;
      // verify the required parameter 'personaInput' is set
      if (personaInput === undefined || personaInput === null) {
        throw new Error("Missing the required parameter 'personaInput' when calling createPersona");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PersonaResponse;
      return this.apiClient.callApi(
        '/personas', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePersona operation.
     * @callback module:api/PersonasApi~deletePersonaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Desactivar persona
     * Desactiva el perfil sin eliminarlo de la base de datos. Rate limit: 30 solicitudes por minuto por IP.
     * @param {String} persona 
     * @param {module:api/PersonasApi~deletePersonaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageResponse}
     */
    deletePersona(persona, callback) {
      let postBody = null;
      // verify the required parameter 'persona' is set
      if (persona === undefined || persona === null) {
        throw new Error("Missing the required parameter 'persona' when calling deletePersona");
      }

      let pathParams = {
        'persona': persona
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageResponse;
      return this.apiClient.callApi(
        '/personas/{persona}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPersona operation.
     * @callback module:api/PersonasApi~getPersonaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener persona por ID
     * Consulta de lectura con rate limit de 120 solicitudes por minuto por IP.
     * @param {String} persona 
     * @param {module:api/PersonasApi~getPersonaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonaResponse}
     */
    getPersona(persona, callback) {
      let postBody = null;
      // verify the required parameter 'persona' is set
      if (persona === undefined || persona === null) {
        throw new Error("Missing the required parameter 'persona' when calling getPersona");
      }

      let pathParams = {
        'persona': persona
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PersonaResponse;
      return this.apiClient.callApi(
        '/personas/{persona}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPersonas operation.
     * @callback module:api/PersonasApi~getPersonasCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonaListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Listar personas (CV ciego)
     * Obtiene talentos activos en formato de CV ciego (sin datos personales identificables). Rate limit: 120 solicitudes por minuto por IP. Se recomienda aplicar filtros para reducir payload y paginar si el volumen crece.
     * @param {Object} opts Optional parameters
     * @param {Boolean} [validado] Filtrar por validación
     * @param {module:model/String} [nivelEducacional] 
     * @param {module:api/PersonasApi~getPersonasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonaListResponse}
     */
    getPersonas(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'validado': opts['validado'],
        'nivel_educacional': opts['nivelEducacional']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PersonaListResponse;
      return this.apiClient.callApi(
        '/personas', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePersona operation.
     * @callback module:api/PersonasApi~updatePersonaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Actualizar persona
     * @param {String} persona 
     * @param {module:model/PersonaInput} personaInput 
     * @param {module:api/PersonasApi~updatePersonaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonaResponse}
     */
    updatePersona(persona, personaInput, callback) {
      let postBody = personaInput;
      // verify the required parameter 'persona' is set
      if (persona === undefined || persona === null) {
        throw new Error("Missing the required parameter 'persona' when calling updatePersona");
      }
      // verify the required parameter 'personaInput' is set
      if (personaInput === undefined || personaInput === null) {
        throw new Error("Missing the required parameter 'personaInput' when calling updatePersona");
      }

      let pathParams = {
        'persona': persona
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PersonaResponse;
      return this.apiClient.callApi(
        '/personas/{persona}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the validarPersona operation.
     * @callback module:api/PersonasApi~validarPersonaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonaValidationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validar persona (solo administración)
     * Marca a una persona como validada para que aparezca en la vitrina. Rate limit: 30 solicitudes por minuto por IP.
     * @param {String} persona 
     * @param {module:api/PersonasApi~validarPersonaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonaValidationResponse}
     */
    validarPersona(persona, callback) {
      let postBody = null;
      // verify the required parameter 'persona' is set
      if (persona === undefined || persona === null) {
        throw new Error("Missing the required parameter 'persona' when calling validarPersona");
      }

      let pathParams = {
        'persona': persona
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PersonaValidationResponse;
      return this.apiClient.callApi(
        '/personas/{persona}/validar', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
