/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.ContactoSolicitado();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactoSolicitado', function() {
    it('should create an instance of ContactoSolicitado', function() {
      // uncomment below and update the code to test ContactoSolicitado
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be.a(ProviEmpleaApi.ContactoSolicitado);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property empresaId (base name: "empresa_id")', function() {
      // uncomment below and update the code to test the property empresaId
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property personaId (base name: "persona_id")', function() {
      // uncomment below and update the code to test the property personaId
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property estado (base name: "estado")', function() {
      // uncomment below and update the code to test the property estado
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property notasAdmin (base name: "notas_admin")', function() {
      // uncomment below and update the code to test the property notasAdmin
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property fechaContacto (base name: "fecha_contacto")', function() {
      // uncomment below and update the code to test the property fechaContacto
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property fechaEntrevista (base name: "fecha_entrevista")', function() {
      // uncomment below and update the code to test the property fechaEntrevista
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property fechaResultado (base name: "fecha_resultado")', function() {
      // uncomment below and update the code to test the property fechaResultado
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property empresa (base name: "empresa")', function() {
      // uncomment below and update the code to test the property empresa
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

    it('should have the property persona (base name: "persona")', function() {
      // uncomment below and update the code to test the property persona
      //var instance = new ProviEmpleaApi.ContactoSolicitado();
      //expect(instance).to.be();
    });

  });

}));
