/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.EmpresaInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmpresaInput', function() {
    it('should create an instance of EmpresaInput', function() {
      // uncomment below and update the code to test EmpresaInput
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be.a(ProviEmpleaApi.EmpresaInput);
    });

    it('should have the property nombreEmpresa (base name: "nombre_empresa")', function() {
      // uncomment below and update the code to test the property nombreEmpresa
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property rutEmpresa (base name: "rut_empresa")', function() {
      // uncomment below and update the code to test the property rutEmpresa
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property logoUrl (base name: "logo_url")', function() {
      // uncomment below and update the code to test the property logoUrl
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property rubro (base name: "rubro")', function() {
      // uncomment below and update the code to test the property rubro
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property tipoEmpresa (base name: "tipo_empresa")', function() {
      // uncomment below and update the code to test the property tipoEmpresa
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property presentacion (base name: "presentacion")', function() {
      // uncomment below and update the code to test the property presentacion
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property beneficios (base name: "beneficios")', function() {
      // uncomment below and update the code to test the property beneficios
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property contactoNombre (base name: "contacto_nombre")', function() {
      // uncomment below and update the code to test the property contactoNombre
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property contactoEmail (base name: "contacto_email")', function() {
      // uncomment below and update the code to test the property contactoEmail
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

    it('should have the property contactoTelefono (base name: "contacto_telefono")', function() {
      // uncomment below and update the code to test the property contactoTelefono
      //var instance = new ProviEmpleaApi.EmpresaInput();
      //expect(instance).to.be();
    });

  });

}));
