/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.Estadisticas();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Estadisticas', function() {
    it('should create an instance of Estadisticas', function() {
      // uncomment below and update the code to test Estadisticas
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be.a(ProviEmpleaApi.Estadisticas);
    });

    it('should have the property totalPersonas (base name: "total_personas")', function() {
      // uncomment below and update the code to test the property totalPersonas
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property personasValidadas (base name: "personas_validadas")', function() {
      // uncomment below and update the code to test the property personasValidadas
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property totalEmpresas (base name: "total_empresas")', function() {
      // uncomment below and update the code to test the property totalEmpresas
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property empresasValidadas (base name: "empresas_validadas")', function() {
      // uncomment below and update the code to test the property empresasValidadas
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property contactosPendientes (base name: "contactos_pendientes")', function() {
      // uncomment below and update the code to test the property contactosPendientes
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property contactosEnProceso (base name: "contactos_en_proceso")', function() {
      // uncomment below and update the code to test the property contactosEnProceso
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

    it('should have the property contactosExitosos (base name: "contactos_exitosos")', function() {
      // uncomment below and update the code to test the property contactosExitosos
      //var instance = new ProviEmpleaApi.Estadisticas();
      //expect(instance).to.be();
    });

  });

}));
