/**
 * ProviEmplea API
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProviEmpleaApi);
  }
}(this, function(expect, ProviEmpleaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProviEmpleaApi.PersonaCVCiego();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonaCVCiego', function() {
    it('should create an instance of PersonaCVCiego', function() {
      // uncomment below and update the code to test PersonaCVCiego
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be.a(ProviEmpleaApi.PersonaCVCiego);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property codigoTalento (base name: "codigo_talento")', function() {
      // uncomment below and update the code to test the property codigoTalento
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property resumen (base name: "resumen")', function() {
      // uncomment below and update the code to test the property resumen
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property nivelEducacional (base name: "nivel_educacional")', function() {
      // uncomment below and update the code to test the property nivelEducacional
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property tituloCarrera (base name: "titulo_carrera")', function() {
      // uncomment below and update the code to test the property tituloCarrera
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property anioEgreso (base name: "anio_egreso")', function() {
      // uncomment below and update the code to test the property anioEgreso
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property aniosExperiencia (base name: "anios_experiencia")', function() {
      // uncomment below and update the code to test the property aniosExperiencia
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property tipoJornada (base name: "tipo_jornada")', function() {
      // uncomment below and update the code to test the property tipoJornada
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property modalidad (base name: "modalidad")', function() {
      // uncomment below and update the code to test the property modalidad
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

    it('should have the property personaDiscapacidad (base name: "persona_discapacidad")', function() {
      // uncomment below and update the code to test the property personaDiscapacidad
      //var instance = new ProviEmpleaApi.PersonaCVCiego();
      //expect(instance).to.be();
    });

  });

}));
